### ISSUE TITLE
Where is “lm/model.pt”？

### ISSUE THREAD

**Issue by yjyGo** [XinnuoXu/mmi_anti_pytorch#4]
I can't find the model.pt.

**Comment by yangjingyingGo** [comment]
I thought the file existed, but it was created after running

**Comment by XinnuoXu** [comment]
Hi @yangjingyingGo , you need to train the language model and you will get the model.pt in file lm/

**Comment by yjyGo** [comment]
> Hi @yangjingyingGo , you need to train the language model and you will get the model.pt in file lm/

Thank you.
